package practica5.mensaje;

public enum KindM {
	M_CONEXION, M_CONFIRMACION_CONEXION, M_LISTA_USUARIOS, M_CONFIRMACION_LISTA_USUARIOS, 
	M_PEDIR_CIUDAD, M_EMITIR_CIUDAD, M_PREPARADO_CS, M_PREPARADO_SC, 
	M_CERRAR_CONEXION, M_CONFIRMACION_CERRAR_CONEXION, M_PAIS_CONSULTADO, M_PAIS_CONSULTADO_CONFIRMACION
}
